library:
  app:
    version: "Version: 1.3"
# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2

# Datasource
spring:
  datasource:
    url: jdbc:h2:file:~/test
    username: admin
    password:
    driver-class-name: org.h2.Driver